// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEBAPITest.Models;

public partial class Category
{
    public int CatId { get; set; }

    public string Name { get; set; }

    public bool? IsActive { get; set; }

    public string ImgPath { get; set; }

    public virtual ICollection<Products> Products { get; set; } = new List<Products>();
}