// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEBAPITest.Models;

public partial class LunchBooking
{
    public int LId { get; set; }

    public int UId { get; set; }

    public int MId { get; set; }

    public DateOnly? Date { get; set; }

    public DateOnly? CreationDate { get; set; }

    public virtual Menu MIdNavigation { get; set; }

    public virtual Users UIdNavigation { get; set; }
}