// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEBAPITest.Models;

public partial class Menu
{
    public int MId { get; set; }
    public DateTime? Date { get; set; }      // matches date column
    public bool? Type { get; set; }          // bit, nullable
    public string? MainDish { get; set; }
    public string? Soup { get; set; }
    public string? Dessert { get; set; }
    public string? Notes { get; set; }
    public int? MaxSeats { get; set; }
    public int? UsedSeats { get; set; }
    public int AvailableSeats { get; set; }  // NOT NULL in DB
    public virtual ICollection<LunchBooking> LunchBookings { get; set; } = new List<LunchBooking>();
}