// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEBAPITest.Models;

public partial class Orders
{
    public int OId { get; set; }              // maps to O_ID
    public int? UserId { get; set; }          // make non-nullable if you enforce it
    public string Status { get; set; } = "Cart";
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
    public decimal? Total { get; set; }
    public string? Notes { get; set; }

    public ICollection<OrderItem> Items { get; set; } = new List<OrderItem>();
}