// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEBAPITest.Models;

public partial class Products
{
    public int ProdId { get; set; }

    public int CatId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal? Price { get; set; }

    public string ImgPath { get; set; }

    public int? DiscountPercent { get; set; }

    public int? MaxStock { get; set; }

    public int? CurStock { get; set; }

    public int? Kcal { get; set; }

    public decimal? Protein { get; set; }

    public decimal? Fat { get; set; }

    public decimal? Carbs { get; set; }

    public decimal? Salt { get; set; }

    public bool? IsFavorite { get; set; }

    public bool IsActive { get; set; }

    public string Allergens { get; set; }

    public int ProductType { get; set; }

    public virtual Category Cat { get; set; }
}