// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WEBAPITest.Models;

public partial class Users
{
    public int UId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int? Role { get; set; }

    public decimal? Balance { get; set; }

    public virtual ICollection<LunchBooking> LunchBookings { get; set; } = new List<LunchBooking>();
}