// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using WEBAPITest.Models; 

namespace WEBAPITest.Data;

public partial class diogoportela_SchoolBarContext : DbContext
{
    public diogoportela_SchoolBarContext()
    {
    }

    public diogoportela_SchoolBarContext(DbContextOptions<diogoportela_SchoolBarContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<LunchBooking> LunchBookings { get; set; }

    public virtual DbSet<Menu> Menus { get; set; }

    public virtual DbSet<Orders> Orders { get; set; }

    public virtual DbSet<Products> Products { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=sql.bsite.net\\MSSQL2016;Initial Catalog=diogoportela_SchoolBar;User ID=diogoportela_SchoolBar;Password=VSBar_;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CatId);

            entity.ToTable("Categories");

            entity.Property(e => e.CatId)
                .ValueGeneratedNever()
                .HasColumnName("Cat_ID");
            entity.Property(e => e.ImgPath)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(30)
                .IsUnicode(false);
        });

        modelBuilder.Entity<LunchBooking>(entity =>
        {
            entity.HasKey(e => e.LId);

            entity.ToTable("LunchBookings");

            entity.Property(e => e.LId)
                .ValueGeneratedNever()
                .HasColumnName("L_ID");
            entity.Property(e => e.MId).HasColumnName("M_ID");
            entity.Property(e => e.UId).HasColumnName("U_ID");

            entity.HasOne(d => d.MIdNavigation).WithMany(p => p.LunchBookings)
                .HasForeignKey(d => d.MId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LunchBooking_Menu");

            entity.HasOne(d => d.UIdNavigation).WithMany(p => p.LunchBookings)
                .HasForeignKey(d => d.UId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LunchBooking_User");
        });

        modelBuilder.Entity<Menu>(entity =>
        {
            entity.HasKey(e => e.MId);
            entity.ToTable("Menus", "dbo"); // adjust schema if different

            entity.Property(e => e.MId).HasColumnName("M_ID");
            entity.Property(e => e.Date).HasColumnType("date");
            entity.Property(e => e.Type); // bit, nullable
            entity.Property(e => e.MainDish).HasMaxLength(50);
            entity.Property(e => e.Soup).HasMaxLength(50);
            entity.Property(e => e.Dessert).HasMaxLength(50);
            entity.Property(e => e.Notes).HasMaxLength(300);
            entity.Property(e => e.MaxSeats);
            entity.Property(e => e.UsedSeats);
            entity.Property(e => e.AvailableSeats); // NOT NULL
        });

        modelBuilder.Entity<Orders>(e =>
        {
            e.ToTable("Orders", "dbo");
            e.HasKey(o => o.OId);
            e.Property(o => o.OId)
                .HasColumnName("O_ID")
                .ValueGeneratedOnAdd(); // ensure DB generates it
            e.Property(o => o.UserId).HasColumnName("U_ID");
            e.Property(o => o.Status).HasMaxLength(20).IsRequired();
            e.Property(o => o.CreatedAt).HasColumnType("datetime2(7)");
            e.Property(o => o.UpdatedAt).HasColumnType("datetime2(7)");
            e.Property(o => o.Total).HasColumnType("decimal(10,2)");
            e.Property(o => o.Notes).HasColumnType("varchar(500)");
        });

        modelBuilder.Entity<OrderItem>(e =>
        {
            e.ToTable("OrderItems", "dbo");
            e.HasKey(oi => oi.OrderItemId);
            e.Property(oi => oi.OrderItemId)
                .HasColumnName("OItem_Id")
                .ValueGeneratedOnAdd();
            e.Property(oi => oi.OrderId).HasColumnName("O_Id");
            e.Property(oi => oi.ProductId).HasColumnName("Prod_ID");
            e.Property(oi => oi.UnitPrice).HasColumnType("decimal(10,2)");
            e.Property(oi => oi.Quantity).IsRequired();
            e.Ignore(oi => oi.MenuId);
            e.Ignore(oi => oi.Menu);

            e.HasOne(oi => oi.Order)
                .WithMany(o => o.Items)
                .HasForeignKey(oi => oi.OrderId)
                .OnDelete(DeleteBehavior.Cascade);

            e.HasOne(oi => oi.Product)
                .WithMany()
                .HasForeignKey(oi => oi.ProductId);
        });

        modelBuilder.Entity<Products>(entity =>
        {
            entity.HasKey(e => e.ProdId);

            entity.ToTable("Products", "dbo");

            entity.Property(e => e.ProdId)
                .ValueGeneratedNever()
                .HasColumnName("Prod_ID");
            entity.Property(e => e.Allergens)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Carbs).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.CatId).HasColumnName("Cat_ID");
            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Fat).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Ignore(e => e.ImgPath); // tells EF not to map this property
            entity.Property(e => e.Price).HasColumnType("money");
            entity.Property(e => e.Protein).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.Salt).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.IsActive).HasColumnType("bit");
            entity.Property(e => e.IsFavorite).HasColumnType("bit");

            entity.HasOne(d => d.Cat).WithMany(p => p.Products)
                .HasForeignKey(d => d.CatId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Product_Category");
            entity.Property(p => p.ProductType).HasColumnName("Type"); // map to the new int column
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.UId);
            entity.ToTable("Users");

            entity.Property(e => e.UId)
                .ValueGeneratedNever()
                .HasColumnName("U_ID");

            entity.Property(e => e.Balance).HasColumnType("money");

            entity.Property(e => e.Email)
                .HasMaxLength(30)
                .IsUnicode(false);

            entity.Property(e => e.FullName)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.Property(e => e.Password)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}